### ISSUE TITLE
Awesome!  verwijderen uit dialoogberichten in scherm

### ISSUE THREAD

**Issue by SusanKroekenstoel** [nedap/Cachet#10]

**Comment by MinThaMie** [comment]
Dit is echt bewust onderdeel van de codebase aan hun kant. Wat is het probleem? Want misschien kunnen we er dan wel wat mee doen in een issue aan hun kant.

**Comment by MinThaMie** [comment]
@SusanKroekenstoel Aangezien we het hier over hebben gehad ga ik deze sluiten :)
