### ISSUE TITLE
Incidentmail aan geabonneerden: titel 'New Incident reported' moet titel van verstoring zijn, met status verstoring erachter.

### ISSUE THREAD

**Issue by SusanKroekenstoel** [nedap/Cachet#11]
![titel bij mail verstoring](https://user-images.githubusercontent.com/8170324/54617215-297f4300-4a61-11e9-8c1c-7afb34abe861.png)

**Comment by MinThaMie** [comment]
CachetHQ#3314

**Comment by MinThaMie** [comment]
Fixed by https://github.com/CachetHQ/Cachet/pull/3540/
