### ISSUE TITLE
Gebruiker is niet automatisch geabonneerd op components die aangemaakt worden na inschrijving

### ISSUE THREAD

**Issue by SusanKroekenstoel** [nedap/Cachet#4]
Wordt er een nieuw component (een nieuwe applicatie) toegevoegd aan de Statuspage, dan zijn bestaande gebruikers nu niet automatisch geabonneerd op updates over dit component, maar moeten ze dit handmatig aanzetten.

Gewenste oplossing:
Nieuwe components standaard toevoegen aan inschrijvingslijstje van gebruikers, zodat het proces omgedraaid is: juist uitschrijven als ze het niet willen.

**Comment by SusanKroekenstoel** [comment]
Kan vermoedelijk niet aangepast worden.

**Comment by stevenkuster** [comment]
Won't fix because it isn't opt-in, which makes it not GDPR compliant.
