### ISSUE TITLE
Aanpassing pop-up bovenin na wijziging abonnementsgegevens

### ISSUE THREAD

**Issue by SusanKroekenstoel** [nedap/Cachet#5]
Ben je al abonnee, en pas je je instellingen aan? Dan verschijnt bovenin - nadat je de wijzigingen hebt doorgevoerd - in de groene balk de volgende notificatie:

Op testpagina in Engels: Awesome. You've been subscribed to email notifications, please check your email to confirm your subscription.

Deze melding moet hier niet komen en doet bovendien niets (er gaat geen mail naar de gebruiker). In plaats daarvan moet de pop-up iets als deze tekst bevatten:

Please check your e-mail to confirm the changes in your subsription.

Vervolgens moet er daadwerkelijk een mail gestuurd worden naar de gebruiker om aan te geven dat de settings veranderd zijn, met daarin b.v. deze tekst:
Please confirm that your e-mail subscription to Nedap healthcare Statuspage statuspage has been changed.

**Comment by stevenkuster** [comment]
This bug is still relevant. The message doesn't reflect the updating of your subscription and no e-mail is send.

Action: Add feature request at Cachet or make a pull request to fix the problem.

**Comment by MinThaMie** [comment]
https://github.com/CachetHQ/Cachet/issues/3561

**Comment by MinThaMie** [comment]
https://github.com/CachetHQ/Cachet/pull/3563

**Comment by MinThaMie** [comment]
Merged
