### ISSUE TITLE
Abonnees kunnen elkaar's instellingen aanpassen

### ISSUE THREAD

**Issue by SusanKroekenstoel** [nedap/Cachet#6]
Situatie:
Vul je het e-mailadres in van iemand anders die al abonnee is, dan is het mogelijk om de settings aan te passen. Er wordt niet gevraagd om een bevestiging van de aanpassing per e-mail.

Gewenste situatie:
Optie 1: na aanpassing van gegevens moeten de aanpassingen bevestigd worden per e-mail. 
(achteraf verifieren zie ook issue 4)
Optie 2: is er bij een e-mailadres al een abonnement bekend, dan wordt er eerst een e-mail verstuurd naar de abonnee, met daarin een link om in het aanpasscherm te kunnen komen. (vooraf verifieren). Dit is misschien moeilijker te realiseren, dus optie 1 is wel goed.

**Comment by SusanKroekenstoel** [comment]
Speelt  in nieuwe opzet niet meer, maar kijken of dit bij nieuwe wijzigingen niet alsnog kan gebeuren.

**Comment by MinThaMie** [comment]
No longer the case in 2.4.0-dev so will close this :)
